// Generated by CoffeeScript 1.3.3
(function() {

  exports.appName = 'app-template';

  exports.analyticsKey = '*****';

  exports.appVersion = '0.0.1';

  exports.debug = true;

  exports.trace = true;

}).call(this);
