// Generated by CoffeeScript 1.3.3
(function() {
  var GoogleTracker,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  GoogleTracker = (function() {

    function GoogleTracker(trackingCode, userId, appVersion) {
      this.event = __bind(this.event, this);

      this.track = __bind(this.track, this);
      window._gaq = typeof _gaq !== "undefined" && _gaq !== null ? _gaq : [];
      window._gaq.push(['_setAccount', trackingCode]);
      window._gaq.push(['_setCustomVar', 1, 'userId', userId, 1]);
      window._gaq.push(['_setCustomVar', 2, 'version', appVersion, 3]);
      (function() {
        var ga, s;
        ga = document.createElement('script');
        ga.type = 'text/javascript';
        ga.async = true;
        ga.src = ('https:' === document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        s = document.getElementsByTagName('script')[0];
        return s.parentNode.insertBefore(ga, s);
      })();
    }

    GoogleTracker.prototype.track = function(page) {
      return window._gaq.push(['_trackPageview', page]);
    };

    GoogleTracker.prototype.event = function(category, action, label, value) {
      if (value != null) {
        return window._gaq.push(['_trackEvent', category, action, label, value]);
      } else {
        return window._gaq.push(['_trackEvent', category, action, label]);
      }
    };

    return GoogleTracker;

  })();

  exports.GoogleTracker = GoogleTracker;

}).call(this);
