// Generated by CoffeeScript 1.3.3
(function() {
  var tracker,
    _this = this;

  exports.tracker = tracker = config.debug ? new spore.DebugTracker() : new googletracker.GoogleTracker(config.analyticsKey, models.session.anonymousUserID, config.appVersion);

  exports.init = function() {
    var app, mainView;
    trace('main.init()');
    window.onerror = function(e) {
      return console.error("encountered an unexpected error: " + e);
    };
    mainView = new views.MainView();
    app = new spore.Spore(sp, config.trace, config.appName, tracker);
    app.register('main', new presenters.MainPresenter(mainView));
    $('img').live('dragstart', function(event) {
      return event.preventDefault();
    });
    return app.go();
  };

}).call(this);
