// Generated by CoffeeScript 1.3.3
(function() {
  var tracker,
    _this = this;

  exports.tracker = tracker = config.debug ? new spore.DebugTracker() : new googletracker.GoogleTracker(config.analyticsKey, models.session.anonymousUserID, config.appVersion);

  exports.init = function() {
    var app, tab1View, tab2View;
    trace('main.init()');
    window.onerror = function(e) {
      return console.error("encountered an unexpected error: " + e);
    };
    tab1View = new views.Tab1View();
    tab2View = new views.Tab2View();
    app = new spore.Spore(sp, config.trace, config.appName, tracker);
    app.register('tab1', new presenters.Tab1Presenter(tab1View));
    app.register('tab2', new presenters.Tab2Presenter(tab2View));
    $('img').live('dragstart', function(event) {
      return event.preventDefault();
    });
    return app.go();
  };

}).call(this);
