// Generated by CoffeeScript 1.3.3
(function() {
  var Tab1Presenter, Tab2Presenter,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Tab1Presenter = (function(_super) {

    __extends(Tab1Presenter, _super);

    function Tab1Presenter(view) {
      this.view = view;
      this.unbind = __bind(this.unbind, this);

      this.show = __bind(this.show, this);

      this.bind = __bind(this.bind, this);

    }

    Tab1Presenter.prototype.bind = function() {};

    Tab1Presenter.prototype.show = function(params) {
      var _this = this;
      this.view.setLoading(true);
      this.view.hide();
      this.view.clear();
      return after(1000, function() {
        _this.view.display();
        return _this.view.show();
      });
    };

    Tab1Presenter.prototype.unbind = function() {
      return this.view.hide();
    };

    return Tab1Presenter;

  })(spore.Presenter);

  exports.Tab1Presenter = Tab1Presenter;

  Tab2Presenter = (function(_super) {

    __extends(Tab2Presenter, _super);

    function Tab2Presenter(view) {
      this.view = view;
      this.unbind = __bind(this.unbind, this);

      this.show = __bind(this.show, this);

      this.bind = __bind(this.bind, this);

    }

    Tab2Presenter.prototype.bind = function() {};

    Tab2Presenter.prototype.show = function(params) {
      var _this = this;
      this.view.setLoading(true);
      this.view.hide();
      this.view.clear();
      return after(1000, function() {
        _this.view.display();
        return _this.view.show();
      });
    };

    Tab2Presenter.prototype.unbind = function() {
      return this.view.hide();
    };

    return Tab2Presenter;

  })(spore.Presenter);

  exports.Tab2Presenter = Tab2Presenter;

}).call(this);
