// Generated by CoffeeScript 1.3.3
(function() {
  var MainPresenter,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  MainPresenter = (function(_super) {

    __extends(MainPresenter, _super);

    function MainPresenter(view) {
      this.view = view;
      this.unbind = __bind(this.unbind, this);

      this.show = __bind(this.show, this);

      this.bind = __bind(this.bind, this);

    }

    MainPresenter.prototype.bind = function() {};

    MainPresenter.prototype.show = function(params) {
      this.view.setLoading(true);
      this.view.hide();
      this.view.clear();
      this.view.display();
      return this.view.show();
    };

    MainPresenter.prototype.unbind = function() {
      return this.view.hide();
    };

    return MainPresenter;

  })(spore.Presenter);

  exports.MainPresenter = MainPresenter;

}).call(this);
