// Generated by CoffeeScript 1.3.3
(function() {
  var csv, id, millisecondsFromText, model, moment, reader, started;

  csv = require('ya-csv');

  moment = require('moment');

  model = [];

  reader = csv.createCsvFileReader("data.csv", {
    separator: ',',
    quote: '"',
    escape: '"',
    comment: ''
  });

  /*
  [ '4',
    'What It\'s All About',
    '0:04:15',
    'The Cure',
    'Close To Me',
    '1985',
    '0:00:40',
    '16%',
    'Y',
    'spotify:track:0L31hObKkJgFW0S4a125Ie',
    '' ]
  */


  millisecondsFromText = function(text) {
    var chunks, min, sec;
    chunks = text.split(':');
    chunks.pop();
    sec = parseInt(chunks.pop());
    min = parseInt(chunks.pop());
    return (min * 60 * 1000) + (sec * 1000);
  };

  started = false;

  id = 0;

  reader.addListener("data", function(data) {
    var record, track;
    if (!started) {
      started = true;
      return;
    }
    track = parseInt(data[0]);
    if (track !== 4) {
      return;
    }
    record = {
      id: id++,
      track: track,
      start: millisecondsFromText(data[6]),
      end: millisecondsFromText(data[10]),
      uri: data[9]
    };
    return model.push(record);
  });

  reader.addListener("end", function() {
    return console.log(JSON.stringify(model));
  });

}).call(this);
